# Generated by Django 5.1.3 on 2024-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='images')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=150, unique=True)),
            ],
        ),
    ]
